name: Build ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Lowercase Registry
        id: registry_case
        run: |
          echo "repo=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.2.4
        with:
          arch: x86_64
          image_name: my-hyprland-os
          image_repo: ghcr.io/${{ steps.registry_case.outputs.repo }}
          image_tag: latest
          version: 41 # Builds an installer based on Fedora 41 (adjust if needed)
          variant: silverblue
          iso_name: GalihOS-latest.iso
